---
docker_network_name: trentonet
force_pull_images: false
web_container_image: ghcr.io/trento-project/trento-web:rolling
web_container_name: trento_web
force_recreate_web_container: false
remove_web_container_image: true
app_web_postgres_host: "host.docker.internal"
wanda_container_image: ghcr.io/trento-project/trento-wanda:rolling
wanda_container_name: trento_wanda
force_recreate_wanda_container: false
remove_wanda_container_image: true
app_wanda_postgres_host: "host.docker.internal"
checks_container_image: ghcr.io/trento-project/checks:rolling
checks_container_name: trento_checks
force_recreate_checks_container: false
remove_checks_container_image: true
app_rabbitmq_host: host.docker.internal
app_prometheus_url: "http://host.docker.internal:9090"
