---
web_server_name: "{{ trento_server_name }}"
web_listen_port: "{{ trento_web_listen_port }}"
web_admin_username: "{{ trento_web_admin_username }}"
web_admin_password: "{{ trento_web_admin_password }}"
web_oas_server_url: "https://{{ trento_server_name }}"
web_postgres_host: "{{ trento_postgres_effective_host }}"
web_postgres_username: "{{ trento_web_postgres_username }}"
web_postgres_password: "{{ trento_web_postgres_password }}"
web_postgres_db: "{{ trento_web_postgres_db }}"
web_postgres_event_store: "{{ trento_web_postgres_event_store }}"
web_amqp_protocol: "{{ amqp_protocol | default('amqp') }}" # `amqp_protocol` is for backwards-compatibility
web_rabbitmq_host: "{{ trento_rabbitmq_effective_host }}"
web_rabbitmq_username: "{{ rabbitmq_username | default(trento_rabbitmq_username) }}" # `rabbimtq_username` for backwards-compatibility
web_rabbitmq_password: "{{ rabbitmq_password | default(trento_rabbitmq_password) }}" # `rabbimtq_password` for backwards-compatibility
web_rabbitmq_vhost: "{{ rabbitmq_vhost | default(trento_rabbitmq_vhost) }}" # `rabbimtq_vhost` for backwards-compatibility
web_wanda_listen_port: "{{ wanda_listen_port | default(trento_wanda_listen_port) }}" # `wanda_listen_port` for backwards-compatibility
web_wanda_proxy_location: "{{ wanda_proxy_location | default(trento_wanda_proxy_location) }}" # `wanda_proxy_location` for backwards-compatibility
web_prometheus_url: "{{ prometheus_url }}"
web_secret_key_base: "{{ secret_key_base }}"
web_access_token_secret: "{{ access_token_secret }}"
web_refresh_token_secret: "{{ refresh_token_secret }}"
web_enable_charts: "{{ enable_charts }}"
web_enable_alerting: "{{ enable_alerting }}"
web_smtp_server: "{{ smtp_server }}"
web_smtp_port: "{{ smtp_port }}"
web_smtp_user: "{{ smtp_user }}"
web_smtp_password: "{{ smtp_password }}"
web_alert_sender: "{{ alert_sender }}"
web_alert_recipient: "{{ alert_recipient }}"
web_enable_oidc: "{{ enable_oidc }}"
web_oidc_client_id: "{{ oidc_client_id }}"
web_oidc_client_secret: "{{ oidc_client_secret }}"
web_oidc_server_base_url: "{{ oidc_server_base_url }}"
web_enable_oauth2: "{{ enable_oauth2 }}"
web_oauth2_client_id: "{{ oauth2_client_id }}"
web_oauth2_client_secret: "{{ oauth2_client_secret }}"
web_oauth2_server_base_url: "{{ oauth2_server_base_url }}"
web_oauth2_authorize_url: "{{ oauth2_authorize_url }}"
web_oauth2_token_url: "{{ oauth2_token_url }}"
web_oauth2_user_url: "{{ oauth2_user_url }}"
web_oauth2_scopes: "{{ oauth2_scopes }}"
web_enable_saml: "{{ enable_saml }}"
web_saml_idp_id: "{{ saml_idp_id }}"
web_saml_idp_nameid_format: "{{ saml_idp_nameid_format }}"
web_saml_sp_dir: "{{ saml_sp_dir }}"
web_saml_sp_id: "{{ saml_sp_id }}"
web_saml_sp_entity_id: "{{ saml_sp_entity_id }}"
web_saml_sp_contact_name: "{{ saml_sp_contact_name }}"
web_saml_sp_contact_email: "{{ saml_sp_contact_email }}"
web_saml_sp_org_name: "{{ saml_sp_org_name }}"
web_saml_sp_org_displayname: "{{ saml_sp_org_displayname }}"
web_saml_sp_org_url: "{{ saml_sp_org_url }}"
web_saml_username_attr_name: "{{ saml_username_attr_name }}"
web_saml_email_attr_name: "{{ saml_email_attr_name }}"
web_saml_firstname_attr_name: "{{ saml_firstname_attr_name }}"
web_saml_lastname_attr_name: "{{ saml_lastname_attr_name }}"
web_saml_metadata_url: "{{ saml_metadata_url }}"
web_saml_metadata_content: "{{ saml_metadata_content }}"
web_saml_sign_requests: "{{ saml_sign_requests }}"
web_saml_sign_metadata: "{{ saml_sign_metadata }}"
web_saml_signed_assertion: "{{ saml_signed_assertion }}"
web_saml_signed_envelopes: "{{ saml_signed_envelopes }}"
