---
install_nginx: "true"
override_nginx_default_conf: "true"
nginx_vhost_filename: "trento"
nginx_vhost_http_listen_port: "80"
nginx_vhost_https_listen_port: "443"
web_upstream_name: "web"
wanda_upstream_name: "wanda"
nginx_ssl_cert_as_base64: "false"
nginx_ssl_key_as_base64: "false"
