---
install_nginx: "true"
override_nginx_default_conf: "true"
grafana_sub_path: "/grafana"
nginx_conf_filename: "trento"
nginx_vhost_http_listen_port: "80"
nginx_vhost_https_listen_port: "443"
web_upstream_name: "web"
wanda_upstream_name: "wanda"
grafana_upstream_name: "grafana"
