---
# DON'T ADD NEW VALUES TO THIS FILE!
# It's only available for backwards-compatibility and smooth
# transition to the new properly named variables. Add new values to
# `main/main.yml`.
web_oas_server_url: "https://{{ app_server_name }}"
wanda_oas_server_url: "https://{{ app_server_name ~ app_wanda_proxy_location }}"
web_postgres_host: "localhost"
wanda_postgres_host: "localhost"
prometheus_url: "http://localhost:9090"
secret_key_base: ""
access_token_secret: ""
refresh_token_secret: ""
enable_api_key: "true"
enable_charts: "true"
enable_alerting:
smtp_server:
smtp_port:
smtp_user:
smtp_password:
alert_sender:
alert_recipient:
install_method: rpm
enable_oidc: "false"
oidc_client_id: ""
oidc_client_secret: ""
oidc_server_base_url: ""
enable_oauth2: "false"
oauth2_client_id: ""
oauth2_client_secret: ""
oauth2_server_base_url: ""
oauth2_authorize_url: ""
oauth2_token_url: ""
oauth2_user_url: ""
oauth2_scopes: "profile email"
enable_saml: "false"
saml_idp_id: ""
saml_idp_nameid_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
saml_sp_dir: "/etc/trento/trento-web/saml"
saml_sp_id: ""
saml_sp_entity_id: ""
saml_sp_contact_name: "Trento SP Admin"
saml_sp_contact_email: "admin@trento.suse.com"
saml_sp_org_name: "Trento SP"
saml_sp_org_displayname: "SAML SP build with Trento"
saml_sp_org_url: "https://www.trento-project.io/"
saml_username_attr_name: "username"
saml_email_attr_name: "email"
saml_firstname_attr_name: "firstName"
saml_lastname_attr_name: "lastName"
saml_metadata_url: ""
saml_metadata_content: ""
saml_sign_requests: "true"
saml_sign_metadata: "true"
saml_signed_assertion: "true"
saml_signed_envelopes: "true"
