---
app_server_name: "{{ trento_server_name }}"
app_web_listen_port: "{{ trento_web_listen_port }}"
app_web_postgres_host: "{{ web_postgres_host }}"
app_web_postgres_username: "{{ trento_web_postgres_username }}"
app_web_postgres_password: "{{ trento_web_postgres_password }}"
app_web_postgres_db: "{{ trento_web_postgres_db }}"
app_web_postgres_event_store: "{{ trento_web_postgres_event_store }}"
app_web_oas_server_url: "{{ web_oas_server_url }}"
app_wanda_listen_port: "{{ trento_wanda_listen_port }}"
app_wanda_postgres_host: "{{ wanda_postgres_host }}"
app_wanda_postgres_username: "{{ trento_wanda_postgres_username }}"
app_wanda_postgres_password: "{{ trento_wanda_postgres_password }}"
app_wanda_postgres_db: "{{ trento_wanda_postgres_db }}"
app_wanda_oas_server_url: "{{ wanda_oas_server_url }}"
app_wanda_proxy_location: "{{ trento_wanda_proxy_location }}"
app_rabbitmq_host: "{{ rabbitmq_host | default('localhost') }}"  # # `rabbitmq_host` for backwards-compatibility
app_rabbitmq_username: "{{ rabbitmq_username | default(trento_rabbitmq_username) }}"  # `rabbimtq_username` for backwards-compatibility
app_rabbitmq_password: "{{ rabbitmq_password | default(trento_rabbitmq_password) }}"  # `rabbimtq_password` for backwards-compatibility
app_rabbitmq_vhost: "{{ rabbitmq_vhost | default(trento_rabbitmq_vhost) }}"  # `rabbimtq_vhost` for backwards-compatibility
app_prometheus_url: "{{ prometheus_url }}"
app_secret_key_base: "{{ secret_key_base }}"
app_access_token_secret: "{{ access_token_secret }}"
app_refresh_token_secret: "{{ refresh_token_secret }}"
app_web_admin_username: "{{ trento_web_admin_username }}"
app_web_admin_password: "{{ trento_web_admin_password }}"
app_enable_api_key: "{{ enable_api_key }}"
app_enable_charts: "{{ enable_charts }}"
app_enable_alerting: "{{ enable_alerting }}"
app_smtp_server: "{{ smtp_server }}"
app_smtp_port: "{{ smtp_port }}"
app_smtp_user: "{{ smtp_user }}"
app_smtp_password: "{{ smtp_password }}"
app_alert_sender: "{{ alert_sender }}"
app_alert_recipient: "{{ alert_recipient }}"
app_amqp_protocol: "{{ amqp_protocol | default('amqp') }}" # `amqp_protocol` is for backwards-compatibility
app_install_method: "{{ install_method }}"
app_enable_oidc: "{{ enable_oidc }}"
app_oidc_client_id: "{{ oidc_client_id }}"
app_oidc_client_secret: "{{ oidc_client_secret }}"
app_oidc_server_base_url: "{{ oidc_server_base_url }}"
app_enable_oauth2: "{{ enable_oauth2 }}"
app_oauth2_client_id: "{{ oauth2_client_id }}"
app_oauth2_client_secret: "{{ oauth2_client_secret }}"
app_oauth2_server_base_url: "{{ oauth2_server_base_url }}"
app_oauth2_authorize_url: "{{ oauth2_authorize_url }}"
app_oauth2_token_url: "{{ oauth2_token_url }}"
app_oauth2_user_url: "{{ oauth2_user_url }}"
app_oauth2_scopes: "{{ oauth2_scopes }}"
app_enable_saml: "{{ enable_saml }}"
app_saml_idp_id: "{{ saml_idp_id }}"
app_saml_idp_nameid_format: "{{ saml_idp_nameid_format }}"
app_saml_sp_dir: "{{ saml_sp_dir }}"
app_saml_sp_id: "{{ saml_sp_id }}"
app_saml_sp_entity_id: "{{ saml_sp_entity_id }}"
app_saml_sp_contact_name: "{{ saml_sp_contact_name }}"
app_saml_sp_contact_email: "{{ saml_sp_contact_email }}"
app_saml_sp_org_name: "{{ saml_sp_org_name }}"
app_saml_sp_org_displayname: "{{ saml_sp_org_displayname }}"
app_saml_sp_org_url: "{{ saml_sp_org_url }}"
app_saml_username_attr_name: "{{ saml_username_attr_name }}"
app_saml_email_attr_name: "{{ saml_email_attr_name }}"
app_saml_firstname_attr_name: "{{ saml_firstname_attr_name }}"
app_saml_lastname_attr_name: "{{ saml_lastname_attr_name }}"
app_saml_metadata_url: "{{ saml_metadata_url }}"
app_saml_metadata_content: "{{ saml_metadata_content }}"
app_saml_sign_requests: "{{ saml_sign_requests }}"
app_saml_sign_metadata: "{{ saml_sign_metadata }}"
app_saml_signed_assertion: "{{ saml_signed_assertion }}"
app_saml_signed_envelopes: "{{ saml_signed_envelopes }}"
