---
rproxy_install: "{{ install_nginx }}"
rproxy_server_name: "{{ trento_server_name }}"
rproxy_web_listen_port: "{{ trento_web_listen_port }}"
rproxy_wanda_listen_port: "{{ trento_wanda_listen_port }}"
rproxy_override_default_conf: "{{ override_nginx_default_conf }}"
rproxy_vhost_filename: "{{ nginx_vhost_filename }}"
rproxy_vhost_http_listen_port: "{{ nginx_vhost_http_listen_port }}"
rproxy_vhost_https_listen_port: "{{ nginx_vhost_https_listen_port }}"
rproxy_web_upstream_name: "{{ web_upstream_name }}"
rproxy_wanda_upstream_name: "{{ wanda_upstream_name }}"
rproxy_wanda_location: "{{ trento_wanda_proxy_location }}"
rproxy_ssl_cert: "{{ nginx_ssl_cert }}"
rproxy_ssl_cert_as_base64: "{{ nginx_ssl_cert_as_base64 }}"
rproxy_ssl_key: "{{ nginx_ssl_key }}"
rproxy_ssl_key_as_base64: "{{ nginx_ssl_key_as_base64 }}"
