---
rproxy_install: "{{ install_nginx }}"
rproxy_server_name: "{{ trento_server_name }}"
rproxy_web_listen_port: "{{ web_listen_port | default(trento_web_listen_port) }}" # `web_listen_port` for backwards-compatibility
rproxy_wanda_listen_port: "{{ wanda_listen_port | default(trento_wanda_listen_port) }}" # `wanda_listen_port` for backwards-compatibility
rproxy_override_default_conf: "{{ override_nginx_default_conf }}"
rproxy_vhost_filename: "{{ nginx_vhost_filename }}"
rproxy_vhost_http_listen_port: "{{ nginx_vhost_http_listen_port }}"
rproxy_vhost_https_listen_port: "{{ nginx_vhost_https_listen_port }}"
rproxy_web_upstream_name: "{{ web_upstream_name }}"
rproxy_wanda_upstream_name: "{{ wanda_upstream_name }}"
rproxy_wanda_location: "{{ wanda_proxy_location | default(trento_wanda_proxy_location) }}" # `wanda_proxy_location` for backwards-compatibility
rproxy_ssl_cert: "{{ nginx_ssl_cert }}"
rproxy_ssl_cert_as_base64: "{{ nginx_ssl_cert_as_base64 }}"
rproxy_ssl_key: "{{ nginx_ssl_key }}"
rproxy_ssl_key_as_base64: "{{ nginx_ssl_key_as_base64 }}"
rproxy_provision_prometheus: "{{ provision_prometheus | bool }}"
rproxy_prometheus_host: "{{ trento_prometheus_effective_host }}"
rproxy_prometheus_port: "{{ trento_prometheus_port }}"
