---
- name: Restart trento-wanda
  ansible.builtin.service:
    name: trento-wanda
    state: restarted

- name: Remove trento docker network
  community.docker.docker_network:
    name: "{{ wanda_docker_network_name }}"
    state: absent
    force: true
