---
- name: Check installation method
  ansible.builtin.assert:
    that:
      - web_install_method is defined
      - web_install_method in ['docker', 'rpm']
    fail_msg: "web_install_method value must be one of: docker|rpm"

- name: Include Docker cleanup tasks
  ansible.builtin.include_tasks: docker_cleanup.yml
  when: web_install_method == 'docker'

- name: Include RPM cleanup tasks
  ansible.builtin.include_tasks: rpm_cleanup.yml
  when: web_install_method == 'rpm'
