# code: language=ansible
---
- name: Include Docker installation variables
  ansible.builtin.include_vars: "../vars/docker.yml"

- name: Stop web container
  community.docker.docker_container:
    name: "{{ web_container_name }}"
    state: absent
    keep_volumes: false
  notify:
    - Remove trento docker network

- name: Remove web container image
  when: web_remove_container_image | bool
  community.docker.docker_image:
    state: absent
    name: "{{ web_container_image }}"
