# code: language=ansible
---
- name: Include Docker installation variables
  ansible.builtin.include_vars: "../vars/docker.yml"

- name: Stop web container
  community.docker.docker_container:
    name: "{{ web_container_name }}"
    state: absent
    keep_volumes: false

- name: Remove web container image
  when: remove_web_container_image | bool
  community.docker.docker_image:
    state: absent
    name: "{{ web_container_image }}"

- name: Remove trento docker network
  community.docker.docker_network:
    name: "{{ web_docker_network_name }}"
    state: absent
    force: true
