---
web_docker_network_name: "{{ trento_docker_network_name }}"
web_force_pull_images: "{{ trento_force_pull_images }}"
web_container_image: ghcr.io/trento-project/trento-web:rolling
web_container_name: "{{ trento_web_container_name }}"
web_force_recreate_web_container: "{{ force_recreate_web_container | default(false) }}"
web_remove_container_image: "{{ remove_web_container_image | default(true) }}"

# Overrides
web_prometheus_url: "http://host.docker.internal:9090"
web_postgres_host: "host.docker.internal"
web_rabbitmq_host: "host.docker.internal"
