---
agent_web_api_key: "{{ undef(hint='API key for Trento Web is mandatory') }}"
agent_trento_server_url: "{{ trento_server_url | default('http://{}'.format(trento_server_name)) }}"
agent_amqp_protocol: "{{ amqp_protocol | default('amqp') }}" # `amqp_protocol` is for backwards-compatibility
agent_rabbitmq_host: "{{ trento_rabbitmq_effective_host }}"
agent_rabbitmq_username: "{{ rabbitmq_username | default(trento_rabbitmq_username) }}" # `rabbimtq_username` for backwards-compatibility
agent_rabbitmq_password: "{{ rabbitmq_password | default(trento_rabbitmq_password) }}" # `rabbimtq_password` for backwards-compatibility
agent_rabbitmq_vhost: "{{ rabbitmq_vhost | default(trento_rabbitmq_vhost) }}" # `rabbimtq_vhost` for backwards-compatibility
agent_install_monitoring_dep: true
agent_server_ca_cert: "{{ undef() }}"
agent_server_ca_cert_as_base64: false
