---
agent_trento_server_url: "{{ trento_server_url | default('http://{}'.format(trento_server_name)) }}"
agent_trento_repository: "{{ trento_repository }}"
agent_web_api_key: "{{ trento_api_key }}"
agent_amqp_protocol: "{{ amqp_protocol | default('amqp') }}" # `amqp_protocol` is for backwards-compatibility
agent_rabbitmq_host: "localhost"
agent_rabbitmq_username: "{{ rabbitmq_username | default(trento_rabbitmq_username) }}"  # `rabbitmq_username` is for backwards-compatibility
agent_rabbitmq_password: "{{ rabbitmq_password | default(trento_rabbitmq_password) }}"  # `rabbitmq_password` is for backwards-compatibility
agent_rabbitmq_vhost: "{{ rabbitmq_vhost | default(trento_rabbitmq_vhost) }}"           # `rabbitmq_vhost` is for backwards-compatibility
