---
agent_trento_server_url: "{{ trento_server_url | default('http://{}'.format(trento_server_name)) }}"  # `trento_server_url` is for backwards-compatibility
agent_trento_repository: "{{ trento_repository }}"
agent_web_api_key: "{{ trento_api_key }}"
agent_amqp_protocol: "{{ amqp_protocol | default('amqp') }}" # `amqp_protocol` is for backwards-compatibility
agent_rabbitmq_host: "localhost:5671"
agent_rabbitmq_username: "{{ rabbitmq_username | default(trento_rabbitmq_username) }}"  # `rabbimtq_username` for backwards-compatibility
agent_rabbitmq_password: "{{ rabbitmq_password | default(trento_rabbitmq_password) }}"  # `rabbimtq_password` for backwards-compatibility
agent_rabbitmq_vhost: "{{ rabbitmq_vhost | default(trento_rabbitmq_vhost) }}"  # `rabbimtq_vhost` for backwards-compatibility
