name: Publish Containers

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
        description: The branch we want to build and publish.
      registry:
        required: false
        type: string
        default: ghcr.io
        description: "The container registry FQDN. Extracted here for clarity, just leave it to default."
      image_name:
        required: true
        type: string
        description: "The container image name, e.g. 'trento-web'"
      tag:
        required: true
        type: string
        description: >-
          The container image tag. Note that this might be either a
          fixed version string, or a moving tag like 'rolling'
      dockerfile:
        required: false
        type: string
        description: "Path to Dockerfile."
      extra_build_args:
        required: false
        type: string
        description: >-
          Additional build arguments that would be passed when
          building the container. Value should be new-line delimited
          string.

jobs:
  detect-version:
    name: Detect version
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/trento-project/continuous-delivery:main
      options: -u 0:0
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Configure git for in-container operations
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Get version from git
        id: extract-version
        run: |
          VERSION=$(/scripts/get_version_from_git.sh)
          echo "version=$VERSION" | tee -a "$GITHUB_OUTPUT"

  build-and-push:
    name: Build and push
    needs: [detect-version]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REPOSITORY: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image_name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - uses: docker/setup-buildx-action@v3

      - name: Log into the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.IMAGE_REPOSITORY }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ needs.detect-version.outputs.version }}
            ${{ inputs.extra_build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
